name: Build (Linux)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04']
        include:
          - os: ubuntu-20.04
            test_target_framework: netcoreapp2.0
            ros_distribution: foxy
            ros_version: 2
          - os: ubuntu-22.04
            test_target_framework: net6.0
            ros_distribution: humble
            ros_version: 2

    runs-on: ${{ matrix.os }}
    env:
      RCLDOTNET_TEST_TARGET_FRAMEWORK: ${{ matrix.test_target_framework }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    # https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804
    - name: Install .NET SDK v2.1
      if: matrix.os == 'ubuntu-20.04'
      run: |
        wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-2.1

    - name: Setup ROS2
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}

    - name: Configure ros2_dotnet workspace
      run: |
        mkdir -p ~/ros2_dotnet_ws/src
        cd ~/ros2_dotnet_ws
        cp ${{github.workspace}}/ros2_dotnet_${{ matrix.ros_distribution }}.repos .
        vcs import src < ros2_dotnet_${{ matrix.ros_distribution }}.repos
        rm -rf src/ros2_dotnet/ros2_dotnet
        cp -r ${{github.workspace}} src/ros2_dotnet/ros2_dotnet
        vcs branch

    - name: Build ros2_dotnet source
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.bash
        cd ~/ros2_dotnet_ws
        colcon build --event-handlers console_cohesion+ console_package_list+

    - name: Run tests
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.bash
        cd ~/ros2_dotnet_ws
        colcon test --event-handlers console_cohesion+ --return-code-on-test-failure --packages-select rcldotnet
